name: FlavorTown
main: hydrogenn.flavorTown.FlavorTown
version: ${project.version}
description: ${project.description}
commands:
  hunger:
    description: Check all information about your current hunger, saturation and nutrition
    usage: /hunger [toggle]